source 'https://rubygems.org'

ruby '2.1.5'

gem 'sinatra', '~> 1.4'
gem 'rack-conneg'
gem 'rack-tracker'
gem 'rake'
gem 'compass'
gem 'bootstrap-sass'
gem 'erubis'
gem 'puma'
gem 'sidekiq'
gem 'foreman'
gem 'pixel_pi'
gem 'httparty'

group :test do
  gem 'rspec'
  gem 'rspec-sidekiq'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-jasmine'
  gem 'capybara'
  gem 'coveralls'
  gem 'jasmine'
  gem 'pry'
  gem 'actionpack'
  gem 'timecop'
end
