black:
  - 0
  - 0
  - 0
blue:
  - 0
  - 0
  - 255
cyan:
  - 0
  - 255
  - 255
green:
  - 0
  - 255
  - 0
magenta:
  - 255
  - 0
  - 255
red:
  - 255
  - 0
  - 0
white:
  - 255
  - 255
  - 255
yellow:
  - 255
  - 255
  - 0
